### ISSUE TITLE
No Thermography data topic?

### ISSUE THREAD

**Issue by rahulsharma11** [clubcapra/capra_thermal_cam#5]
Hi,
I checked the code is based on USB_CAM node. I am using flir lepton with purethermal2 board. I get the Display image but not the thermography data.

Any scope for that? or any link for the same?

Thanks.

**Comment by saxtot** [comment]
Hi @rahulsharma11,

For our project, the data you are looking for is not needed, hence why it is not there.

The best I can offer you is the flir_lepton ROS repository available here: [https://github.com/angetria/flir_lepton](url)
I haven't tested it myself and it seems to have unresolved issues, but, looking at the flir_lepton_msgs package, this looks like a decent option for you.

Sorry I can't help more, good luck on your project!
